/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as StorybookChroniclesRouteImport } from './routes/storybook-chronicles'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SpoilerNotesRouteImport } from './routes/spoiler-notes'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as PowerSystemsRouteImport } from './routes/power-systems'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as FactionsRouteImport } from './routes/factions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StorybookChroniclesIndexRouteImport } from './routes/storybook-chronicles.index'
import { Route as CharactersIndexRouteImport } from './routes/characters.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StorybookChroniclesTimelineRouteImport } from './routes/storybook-chronicles.timeline'
import { Route as StorybookChroniclesDevelopmentProcessRouteImport } from './routes/storybook-chronicles.development-process'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as CharactersSlugRouteImport } from './routes/characters.$slug'
import { Route as AdminLocationsIndexRouteImport } from './routes/admin.locations.index'
import { Route as AdminFactionsIndexRouteImport } from './routes/admin.factions.index'
import { Route as AdminCharactersIndexRouteImport } from './routes/admin.characters.index'
import { Route as AdminLocationsNewRouteImport } from './routes/admin.locations.new'
import { Route as AdminLocationsIdRouteImport } from './routes/admin.locations.$id'
import { Route as AdminFactionsNewRouteImport } from './routes/admin.factions.new'
import { Route as AdminFactionsIdRouteImport } from './routes/admin.factions.$id'
import { Route as AdminCharactersNewRouteImport } from './routes/admin.characters.new'
import { Route as AdminCharactersIdRouteImport } from './routes/admin.characters.$id'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const StorybookChroniclesRoute = StorybookChroniclesRouteImport.update({
  id: '/storybook-chronicles',
  path: '/storybook-chronicles',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoilerNotesRoute = SpoilerNotesRouteImport.update({
  id: '/spoiler-notes',
  path: '/spoiler-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerSystemsRoute = PowerSystemsRouteImport.update({
  id: '/power-systems',
  path: '/power-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const FactionsRoute = FactionsRouteImport.update({
  id: '/factions',
  path: '/factions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorybookChroniclesIndexRoute =
  StorybookChroniclesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StorybookChroniclesRoute,
  } as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StorybookChroniclesTimelineRoute =
  StorybookChroniclesTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => StorybookChroniclesRoute,
  } as any)
const StorybookChroniclesDevelopmentProcessRoute =
  StorybookChroniclesDevelopmentProcessRouteImport.update({
    id: '/development-process',
    path: '/development-process',
    getParentRoute: () => StorybookChroniclesRoute,
  } as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const CharactersSlugRoute = CharactersSlugRouteImport.update({
  id: '/characters/$slug',
  path: '/characters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocationsIndexRoute = AdminLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFactionsIndexRoute = AdminFactionsIndexRouteImport.update({
  id: '/factions/',
  path: '/factions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCharactersIndexRoute = AdminCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsNewRoute = AdminLocationsNewRouteImport.update({
  id: '/locations/new',
  path: '/locations/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsIdRoute = AdminLocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFactionsNewRoute = AdminFactionsNewRouteImport.update({
  id: '/factions/new',
  path: '/factions/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFactionsIdRoute = AdminFactionsIdRouteImport.update({
  id: '/factions/$id',
  path: '/factions/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCharactersNewRoute = AdminCharactersNewRouteImport.update({
  id: '/characters/new',
  path: '/characters/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCharactersIdRoute = AdminCharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/factions': typeof FactionsRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/power-systems': typeof PowerSystemsRoute
  '/reset': typeof ResetRoute
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/spoiler-notes': typeof SpoilerNotesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/storybook-chronicles': typeof StorybookChroniclesRouteWithChildren
  '/worlds': typeof WorldsRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/storybook-chronicles/development-process': typeof StorybookChroniclesDevelopmentProcessRoute
  '/storybook-chronicles/timeline': typeof StorybookChroniclesTimelineRoute
  '/admin/': typeof AdminIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/storybook-chronicles/': typeof StorybookChroniclesIndexRoute
  '/admin/characters/$id': typeof AdminCharactersIdRoute
  '/admin/characters/new': typeof AdminCharactersNewRoute
  '/admin/factions/$id': typeof AdminFactionsIdRoute
  '/admin/factions/new': typeof AdminFactionsNewRoute
  '/admin/locations/$id': typeof AdminLocationsIdRoute
  '/admin/locations/new': typeof AdminLocationsNewRoute
  '/admin/characters/': typeof AdminCharactersIndexRoute
  '/admin/factions/': typeof AdminFactionsIndexRoute
  '/admin/locations/': typeof AdminLocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/factions': typeof FactionsRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/power-systems': typeof PowerSystemsRoute
  '/reset': typeof ResetRoute
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/spoiler-notes': typeof SpoilerNotesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/worlds': typeof WorldsRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/storybook-chronicles/development-process': typeof StorybookChroniclesDevelopmentProcessRoute
  '/storybook-chronicles/timeline': typeof StorybookChroniclesTimelineRoute
  '/admin': typeof AdminIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/storybook-chronicles': typeof StorybookChroniclesIndexRoute
  '/admin/characters/$id': typeof AdminCharactersIdRoute
  '/admin/characters/new': typeof AdminCharactersNewRoute
  '/admin/factions/$id': typeof AdminFactionsIdRoute
  '/admin/factions/new': typeof AdminFactionsNewRoute
  '/admin/locations/$id': typeof AdminLocationsIdRoute
  '/admin/locations/new': typeof AdminLocationsNewRoute
  '/admin/characters': typeof AdminCharactersIndexRoute
  '/admin/factions': typeof AdminFactionsIndexRoute
  '/admin/locations': typeof AdminLocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/factions': typeof FactionsRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/power-systems': typeof PowerSystemsRoute
  '/reset': typeof ResetRoute
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/spoiler-notes': typeof SpoilerNotesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/storybook-chronicles': typeof StorybookChroniclesRouteWithChildren
  '/worlds': typeof WorldsRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/storybook-chronicles/development-process': typeof StorybookChroniclesDevelopmentProcessRoute
  '/storybook-chronicles/timeline': typeof StorybookChroniclesTimelineRoute
  '/admin/': typeof AdminIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/storybook-chronicles/': typeof StorybookChroniclesIndexRoute
  '/admin/characters/$id': typeof AdminCharactersIdRoute
  '/admin/characters/new': typeof AdminCharactersNewRoute
  '/admin/factions/$id': typeof AdminFactionsIdRoute
  '/admin/factions/new': typeof AdminFactionsNewRoute
  '/admin/locations/$id': typeof AdminLocationsIdRoute
  '/admin/locations/new': typeof AdminLocationsNewRoute
  '/admin/characters/': typeof AdminCharactersIndexRoute
  '/admin/factions/': typeof AdminFactionsIndexRoute
  '/admin/locations/': typeof AdminLocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/factions'
    | '/locations'
    | '/login'
    | '/portfolio'
    | '/power-systems'
    | '/reset'
    | '/resume'
    | '/skills'
    | '/spoiler-notes'
    | '/stories'
    | '/storybook-chronicles'
    | '/worlds'
    | '/characters/$slug'
    | '/stories/$slug'
    | '/storybook-chronicles/development-process'
    | '/storybook-chronicles/timeline'
    | '/admin/'
    | '/characters/'
    | '/storybook-chronicles/'
    | '/admin/characters/$id'
    | '/admin/characters/new'
    | '/admin/factions/$id'
    | '/admin/factions/new'
    | '/admin/locations/$id'
    | '/admin/locations/new'
    | '/admin/characters/'
    | '/admin/factions/'
    | '/admin/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/factions'
    | '/locations'
    | '/login'
    | '/portfolio'
    | '/power-systems'
    | '/reset'
    | '/resume'
    | '/skills'
    | '/spoiler-notes'
    | '/stories'
    | '/worlds'
    | '/characters/$slug'
    | '/stories/$slug'
    | '/storybook-chronicles/development-process'
    | '/storybook-chronicles/timeline'
    | '/admin'
    | '/characters'
    | '/storybook-chronicles'
    | '/admin/characters/$id'
    | '/admin/characters/new'
    | '/admin/factions/$id'
    | '/admin/factions/new'
    | '/admin/locations/$id'
    | '/admin/locations/new'
    | '/admin/characters'
    | '/admin/factions'
    | '/admin/locations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/factions'
    | '/locations'
    | '/login'
    | '/portfolio'
    | '/power-systems'
    | '/reset'
    | '/resume'
    | '/skills'
    | '/spoiler-notes'
    | '/stories'
    | '/storybook-chronicles'
    | '/worlds'
    | '/characters/$slug'
    | '/stories/$slug'
    | '/storybook-chronicles/development-process'
    | '/storybook-chronicles/timeline'
    | '/admin/'
    | '/characters/'
    | '/storybook-chronicles/'
    | '/admin/characters/$id'
    | '/admin/characters/new'
    | '/admin/factions/$id'
    | '/admin/factions/new'
    | '/admin/locations/$id'
    | '/admin/locations/new'
    | '/admin/characters/'
    | '/admin/factions/'
    | '/admin/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FactionsRoute: typeof FactionsRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  PowerSystemsRoute: typeof PowerSystemsRoute
  ResetRoute: typeof ResetRoute
  ResumeRoute: typeof ResumeRoute
  SkillsRoute: typeof SkillsRoute
  SpoilerNotesRoute: typeof SpoilerNotesRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  StorybookChroniclesRoute: typeof StorybookChroniclesRouteWithChildren
  WorldsRoute: typeof WorldsRoute
  CharactersSlugRoute: typeof CharactersSlugRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storybook-chronicles': {
      id: '/storybook-chronicles'
      path: '/storybook-chronicles'
      fullPath: '/storybook-chronicles'
      preLoaderRoute: typeof StorybookChroniclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoiler-notes': {
      id: '/spoiler-notes'
      path: '/spoiler-notes'
      fullPath: '/spoiler-notes'
      preLoaderRoute: typeof SpoilerNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-systems': {
      id: '/power-systems'
      path: '/power-systems'
      fullPath: '/power-systems'
      preLoaderRoute: typeof PowerSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factions': {
      id: '/factions'
      path: '/factions'
      fullPath: '/factions'
      preLoaderRoute: typeof FactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storybook-chronicles/': {
      id: '/storybook-chronicles/'
      path: '/'
      fullPath: '/storybook-chronicles/'
      preLoaderRoute: typeof StorybookChroniclesIndexRouteImport
      parentRoute: typeof StorybookChroniclesRoute
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/storybook-chronicles/timeline': {
      id: '/storybook-chronicles/timeline'
      path: '/timeline'
      fullPath: '/storybook-chronicles/timeline'
      preLoaderRoute: typeof StorybookChroniclesTimelineRouteImport
      parentRoute: typeof StorybookChroniclesRoute
    }
    '/storybook-chronicles/development-process': {
      id: '/storybook-chronicles/development-process'
      path: '/development-process'
      fullPath: '/storybook-chronicles/development-process'
      preLoaderRoute: typeof StorybookChroniclesDevelopmentProcessRouteImport
      parentRoute: typeof StorybookChroniclesRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/characters/$slug': {
      id: '/characters/$slug'
      path: '/characters/$slug'
      fullPath: '/characters/$slug'
      preLoaderRoute: typeof CharactersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locations/': {
      id: '/admin/locations/'
      path: '/locations'
      fullPath: '/admin/locations/'
      preLoaderRoute: typeof AdminLocationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/factions/': {
      id: '/admin/factions/'
      path: '/factions'
      fullPath: '/admin/factions/'
      preLoaderRoute: typeof AdminFactionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/characters/': {
      id: '/admin/characters/'
      path: '/characters'
      fullPath: '/admin/characters/'
      preLoaderRoute: typeof AdminCharactersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations/new': {
      id: '/admin/locations/new'
      path: '/locations/new'
      fullPath: '/admin/locations/new'
      preLoaderRoute: typeof AdminLocationsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations/$id': {
      id: '/admin/locations/$id'
      path: '/locations/$id'
      fullPath: '/admin/locations/$id'
      preLoaderRoute: typeof AdminLocationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/factions/new': {
      id: '/admin/factions/new'
      path: '/factions/new'
      fullPath: '/admin/factions/new'
      preLoaderRoute: typeof AdminFactionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/factions/$id': {
      id: '/admin/factions/$id'
      path: '/factions/$id'
      fullPath: '/admin/factions/$id'
      preLoaderRoute: typeof AdminFactionsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/characters/new': {
      id: '/admin/characters/new'
      path: '/characters/new'
      fullPath: '/admin/characters/new'
      preLoaderRoute: typeof AdminCharactersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/characters/$id': {
      id: '/admin/characters/$id'
      path: '/characters/$id'
      fullPath: '/admin/characters/$id'
      preLoaderRoute: typeof AdminCharactersIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCharactersIdRoute: typeof AdminCharactersIdRoute
  AdminCharactersNewRoute: typeof AdminCharactersNewRoute
  AdminFactionsIdRoute: typeof AdminFactionsIdRoute
  AdminFactionsNewRoute: typeof AdminFactionsNewRoute
  AdminLocationsIdRoute: typeof AdminLocationsIdRoute
  AdminLocationsNewRoute: typeof AdminLocationsNewRoute
  AdminCharactersIndexRoute: typeof AdminCharactersIndexRoute
  AdminFactionsIndexRoute: typeof AdminFactionsIndexRoute
  AdminLocationsIndexRoute: typeof AdminLocationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCharactersIdRoute: AdminCharactersIdRoute,
  AdminCharactersNewRoute: AdminCharactersNewRoute,
  AdminFactionsIdRoute: AdminFactionsIdRoute,
  AdminFactionsNewRoute: AdminFactionsNewRoute,
  AdminLocationsIdRoute: AdminLocationsIdRoute,
  AdminLocationsNewRoute: AdminLocationsNewRoute,
  AdminCharactersIndexRoute: AdminCharactersIndexRoute,
  AdminFactionsIndexRoute: AdminFactionsIndexRoute,
  AdminLocationsIndexRoute: AdminLocationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

interface StorybookChroniclesRouteChildren {
  StorybookChroniclesDevelopmentProcessRoute: typeof StorybookChroniclesDevelopmentProcessRoute
  StorybookChroniclesTimelineRoute: typeof StorybookChroniclesTimelineRoute
  StorybookChroniclesIndexRoute: typeof StorybookChroniclesIndexRoute
}

const StorybookChroniclesRouteChildren: StorybookChroniclesRouteChildren = {
  StorybookChroniclesDevelopmentProcessRoute:
    StorybookChroniclesDevelopmentProcessRoute,
  StorybookChroniclesTimelineRoute: StorybookChroniclesTimelineRoute,
  StorybookChroniclesIndexRoute: StorybookChroniclesIndexRoute,
}

const StorybookChroniclesRouteWithChildren =
  StorybookChroniclesRoute._addFileChildren(StorybookChroniclesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FactionsRoute: FactionsRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  PowerSystemsRoute: PowerSystemsRoute,
  ResetRoute: ResetRoute,
  ResumeRoute: ResumeRoute,
  SkillsRoute: SkillsRoute,
  SpoilerNotesRoute: SpoilerNotesRoute,
  StoriesRoute: StoriesRouteWithChildren,
  StorybookChroniclesRoute: StorybookChroniclesRouteWithChildren,
  WorldsRoute: WorldsRoute,
  CharactersSlugRoute: CharactersSlugRoute,
  CharactersIndexRoute: CharactersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
