/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as StorybookChroniclesRouteImport } from './routes/storybook-chronicles'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SpoilerNotesRouteImport } from './routes/spoiler-notes'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as PowerSystemsRouteImport } from './routes/power-systems'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FactionsRouteImport } from './routes/factions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StorybookChroniclesIndexRouteImport } from './routes/storybook-chronicles.index'
import { Route as CharactersIndexRouteImport } from './routes/characters.index'
import { Route as StorybookChroniclesTimelineRouteImport } from './routes/storybook-chronicles.timeline'
import { Route as StorybookChroniclesDevelopmentProcessRouteImport } from './routes/storybook-chronicles.development-process'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as CharactersSlugRouteImport } from './routes/characters.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const StorybookChroniclesRoute = StorybookChroniclesRouteImport.update({
  id: '/storybook-chronicles',
  path: '/storybook-chronicles',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoilerNotesRoute = SpoilerNotesRouteImport.update({
  id: '/spoiler-notes',
  path: '/spoiler-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerSystemsRoute = PowerSystemsRouteImport.update({
  id: '/power-systems',
  path: '/power-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FactionsRoute = FactionsRouteImport.update({
  id: '/factions',
  path: '/factions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorybookChroniclesIndexRoute =
  StorybookChroniclesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StorybookChroniclesRoute,
  } as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorybookChroniclesTimelineRoute =
  StorybookChroniclesTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => StorybookChroniclesRoute,
  } as any)
const StorybookChroniclesDevelopmentProcessRoute =
  StorybookChroniclesDevelopmentProcessRouteImport.update({
    id: '/development-process',
    path: '/development-process',
    getParentRoute: () => StorybookChroniclesRoute,
  } as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const CharactersSlugRoute = CharactersSlugRouteImport.update({
  id: '/characters/$slug',
  path: '/characters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/factions': typeof FactionsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/portfolio': typeof PortfolioRoute
  '/power-systems': typeof PowerSystemsRoute
  '/reset': typeof ResetRoute
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/spoiler-notes': typeof SpoilerNotesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/storybook-chronicles': typeof StorybookChroniclesRouteWithChildren
  '/worlds': typeof WorldsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/storybook-chronicles/development-process': typeof StorybookChroniclesDevelopmentProcessRoute
  '/storybook-chronicles/timeline': typeof StorybookChroniclesTimelineRoute
  '/characters/': typeof CharactersIndexRoute
  '/storybook-chronicles/': typeof StorybookChroniclesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/factions': typeof FactionsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/portfolio': typeof PortfolioRoute
  '/power-systems': typeof PowerSystemsRoute
  '/reset': typeof ResetRoute
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/spoiler-notes': typeof SpoilerNotesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/worlds': typeof WorldsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/storybook-chronicles/development-process': typeof StorybookChroniclesDevelopmentProcessRoute
  '/storybook-chronicles/timeline': typeof StorybookChroniclesTimelineRoute
  '/characters': typeof CharactersIndexRoute
  '/storybook-chronicles': typeof StorybookChroniclesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/factions': typeof FactionsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/portfolio': typeof PortfolioRoute
  '/power-systems': typeof PowerSystemsRoute
  '/reset': typeof ResetRoute
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/spoiler-notes': typeof SpoilerNotesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/storybook-chronicles': typeof StorybookChroniclesRouteWithChildren
  '/worlds': typeof WorldsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/storybook-chronicles/development-process': typeof StorybookChroniclesDevelopmentProcessRoute
  '/storybook-chronicles/timeline': typeof StorybookChroniclesTimelineRoute
  '/characters/': typeof CharactersIndexRoute
  '/storybook-chronicles/': typeof StorybookChroniclesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/factions'
    | '/login'
    | '/mcp'
    | '/portfolio'
    | '/power-systems'
    | '/reset'
    | '/resume'
    | '/skills'
    | '/spoiler-notes'
    | '/stories'
    | '/storybook-chronicles'
    | '/worlds'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/characters/$slug'
    | '/stories/$slug'
    | '/storybook-chronicles/development-process'
    | '/storybook-chronicles/timeline'
    | '/characters/'
    | '/storybook-chronicles/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/factions'
    | '/login'
    | '/mcp'
    | '/portfolio'
    | '/power-systems'
    | '/reset'
    | '/resume'
    | '/skills'
    | '/spoiler-notes'
    | '/stories'
    | '/worlds'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/characters/$slug'
    | '/stories/$slug'
    | '/storybook-chronicles/development-process'
    | '/storybook-chronicles/timeline'
    | '/characters'
    | '/storybook-chronicles'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/factions'
    | '/login'
    | '/mcp'
    | '/portfolio'
    | '/power-systems'
    | '/reset'
    | '/resume'
    | '/skills'
    | '/spoiler-notes'
    | '/stories'
    | '/storybook-chronicles'
    | '/worlds'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/characters/$slug'
    | '/stories/$slug'
    | '/storybook-chronicles/development-process'
    | '/storybook-chronicles/timeline'
    | '/characters/'
    | '/storybook-chronicles/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  FactionsRoute: typeof FactionsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PortfolioRoute: typeof PortfolioRoute
  PowerSystemsRoute: typeof PowerSystemsRoute
  ResetRoute: typeof ResetRoute
  ResumeRoute: typeof ResumeRoute
  SkillsRoute: typeof SkillsRoute
  SpoilerNotesRoute: typeof SpoilerNotesRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  StorybookChroniclesRoute: typeof StorybookChroniclesRouteWithChildren
  WorldsRoute: typeof WorldsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CharactersSlugRoute: typeof CharactersSlugRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storybook-chronicles': {
      id: '/storybook-chronicles'
      path: '/storybook-chronicles'
      fullPath: '/storybook-chronicles'
      preLoaderRoute: typeof StorybookChroniclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoiler-notes': {
      id: '/spoiler-notes'
      path: '/spoiler-notes'
      fullPath: '/spoiler-notes'
      preLoaderRoute: typeof SpoilerNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-systems': {
      id: '/power-systems'
      path: '/power-systems'
      fullPath: '/power-systems'
      preLoaderRoute: typeof PowerSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factions': {
      id: '/factions'
      path: '/factions'
      fullPath: '/factions'
      preLoaderRoute: typeof FactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storybook-chronicles/': {
      id: '/storybook-chronicles/'
      path: '/'
      fullPath: '/storybook-chronicles/'
      preLoaderRoute: typeof StorybookChroniclesIndexRouteImport
      parentRoute: typeof StorybookChroniclesRoute
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storybook-chronicles/timeline': {
      id: '/storybook-chronicles/timeline'
      path: '/timeline'
      fullPath: '/storybook-chronicles/timeline'
      preLoaderRoute: typeof StorybookChroniclesTimelineRouteImport
      parentRoute: typeof StorybookChroniclesRoute
    }
    '/storybook-chronicles/development-process': {
      id: '/storybook-chronicles/development-process'
      path: '/development-process'
      fullPath: '/storybook-chronicles/development-process'
      preLoaderRoute: typeof StorybookChroniclesDevelopmentProcessRouteImport
      parentRoute: typeof StorybookChroniclesRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/characters/$slug': {
      id: '/characters/$slug'
      path: '/characters/$slug'
      fullPath: '/characters/$slug'
      preLoaderRoute: typeof CharactersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

interface StorybookChroniclesRouteChildren {
  StorybookChroniclesDevelopmentProcessRoute: typeof StorybookChroniclesDevelopmentProcessRoute
  StorybookChroniclesTimelineRoute: typeof StorybookChroniclesTimelineRoute
  StorybookChroniclesIndexRoute: typeof StorybookChroniclesIndexRoute
}

const StorybookChroniclesRouteChildren: StorybookChroniclesRouteChildren = {
  StorybookChroniclesDevelopmentProcessRoute:
    StorybookChroniclesDevelopmentProcessRoute,
  StorybookChroniclesTimelineRoute: StorybookChroniclesTimelineRoute,
  StorybookChroniclesIndexRoute: StorybookChroniclesIndexRoute,
}

const StorybookChroniclesRouteWithChildren =
  StorybookChroniclesRoute._addFileChildren(StorybookChroniclesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  FactionsRoute: FactionsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PortfolioRoute: PortfolioRoute,
  PowerSystemsRoute: PowerSystemsRoute,
  ResetRoute: ResetRoute,
  ResumeRoute: ResumeRoute,
  SkillsRoute: SkillsRoute,
  SpoilerNotesRoute: SpoilerNotesRoute,
  StoriesRoute: StoriesRouteWithChildren,
  StorybookChroniclesRoute: StorybookChroniclesRouteWithChildren,
  WorldsRoute: WorldsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CharactersSlugRoute: CharactersSlugRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
